### ISSUE TITLE
Negatively impacts AP slugs

### ISSUE THREAD

**Issue by HamsterGabe** [mrcreepysos/msga#1]
I found this out after seeing my dedicated anti-sniper shotgun was doing drastically less damage at long range, especially on servers I'm not hosting. I use berserk with it so it _should_ be one-shotting snipers on the body even without overkill. It also seems to affect other ammo types, although less so.
![image](https://github.com/mrcreepysos/msga/assets/134323134/05ffd1cd-a5aa-4c6e-99cb-4fdd95ba17b4)
![image](https://github.com/mrcreepysos/msga/assets/134323134/982a3ba9-3370-4b45-b448-2f3a17854377)

**Comment by mrcreepysos** [comment]
closed as it's fixed now
